version: '3'
services:
  database:
    image: postgres:14
    env_file: .postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data
  fastapi:
    build: ./
    image: fastapi-image
    env_file: .fastapi.env
    depends_on:
      - database
    ports:
      - '8010:8010'
volumes:
  pgdata: